favicon: null
name: shannonwilkinson
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 1
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2885305
analytics:
  twitter: null
  google: null
  facebook: null
